.TH twoftpd-auth 1
.SH NAME
twoftpd-auth \- TwoFTPD authentication front-end
.SH SYNOPSIS
.B twoftpd-auth
.B cvmodule
.B twoftpd-xfer
.SH DESCRIPTION
.B twoftpd-auth
reads a username and password from the network and authenticates them
using the CVM module
.BR cvmodule .
If the authentication succeeds, it sets the environment variables
.BR UID ,
.BR GID ,
and
.B HOME
to the user's UID, GID, home directory, and login name respectively,
and then executes
.BR twoftpd-xfer .
.SH ENVIRONMENT
.TP
.B TIMEOUT
The maximum number of seconds to wait for command input.
.SH SEE ALSO
twoftpd-xfer(1)
