.TH twoftpd-switch 1
.SH NAME
twoftpd-switch \- TwoFTPD back-end switcher.
.SH SYNOPSIS
.B twoftpd-switch
.SH DESCRIPTION
.B twoftpd-switch
examines the value of
.B $SHELL
to determine which back-end to execute.  If
.B $SHELL_WRITEONLY
is set and matches the value of
.BR $SHELL ,
.B twoftpd-drop
is executed.  If
.B $SHELL_READONLY
is set and matches the value of
.BR $SHELL ,
.B twoftpd-anon
is executed.  Otherwise,
.B twoftpd-xfer
is executed.
.SH NOTES
.B twoftpd-switch
prefixes the commands with the path in which the programs were
installed.
.SH SEE ALSO
twoftpd-xfer(1)
