.TH twoftpd-auth 1
.SH NAME
twoftpd-auth \- TwoFTPD authentication front-end
.SH SYNOPSIS
.B twoftpd-auth
.B twoftpd-xfer
[
.B -- twoftpd-anon
]
.SH DESCRIPTION
.B twoftpd-auth
reads a username and password from the network and authenticates them.
If the authentication succeeds, it sets the environment variables
.BR UID ,
.BR GID ,
and
.B HOME
to the user's UID, GID, home directory, and login name respectively,
and then executes
.BR twoftpd-xfer .
.P
If the
.B twoftpd-anon
parameter is present, the environment variables
.BR ANON_UID ,
.BR ANON_GID ,
and
.B ANON_HOME
must also be set, and
.B twoftpd-auth
will accept either
.I anonymous
or
.I ftp
as usernames with no password required.
Upon anonymous login,
.B twoftpd-auth
will set
.BR UID ,
.BR GID ,
and
.B HOME
to their
.B ANON_
counterparts, additionally set
.BR CHROOT ,
and execute
.BR twoftpd-anon .
.SH ENVIRONMENT
.TP
.B TIMEOUT
The maximum number of seconds to wait for command input.
.SH SEE ALSO
twoftpd-xfer(1)
